tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "microsoft/git"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"
brew "autojump"
brew "bat"
brew "cheat"
brew "cmatrix"
brew "exa"
brew "figlet"
brew "gh"
brew "git"
brew "unbound"
brew "gnupg"
brew "httpie"
brew "hugo"
brew "jq"
brew "mas"
brew "neovim"
brew "nghttp2"
brew "openjdk"
brew "php"
brew "terraform"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "zsh"
brew "zsh-syntax-highlighting"
cask "calibre"
cask "font-fira-code"
cask "git-credential-manager-core"
cask "visual-studio-code"
mas "Kindle", id: 405399194
mas "Magnet", id: 441258766
mas "Microsoft Excel", id: 462058435
mas "MINDSTORMS", id: 1515448947
mas "mSecure", id: 1157750250
mas "Todoist", id: 585829637
